openapi: 3.0.1
info:
  title: GETMYBOOK GATEWAY
  description: The GETMYBOOK GATEWAY API documentation
  contact:
    name: GETMYBOOK
    email: mj.eng8191@gmail.com
  version: 0.0.0
paths:
  /users/{userId}:
    get:
      summary: Get a user by ID
      parameters:
        - name: userId
          required: true
          in: path
          schema:
            type: integer
      responses:
        '200':
          description: A single user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - userName
        - password
        - role
      properties:
        id:
          type: integer
        name:
          type: string
        userName:
          type: string
        password:
          type: string
        role:
          type: string
          enum:
            - admin
            - agent
            - buyer
            - seller
        city:
          type: string
        pin:
          type: integer
        address:
          type: string
        contact:
          type: integer

    UserEtended:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            createdOn:
              type: string
            updatedOn:
              type: string













