openapi: 3.0.1
info:
  title: user
  description: user API documentation
  contact:
    name: GETMYBOOK
    email: mj.eng8191@gmail.com
  version: 0.0.0
paths:
  /users/{userName}:
    get:
      summary: Get a user by userName
      parameters:
        - name: userName
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: A single user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:



    User:
      required:
        - userName
        - password
        - firstName
        - lastName

      properties:
        firstName:
          type: string
        lastName:
          type: string
        userName:
          type: string
        password:
          type: string
        contact:
          type: number
        role:
          type: string
          enum:
            - admin
            - user
        createdOn:
          type: string
        updatedOn:
          type: string
        createdBy:
          type: string
        updatedBy:
          type: string


    Address:
      required:
        - id
        - userName
        - addressType
        - line1
        - line2
        - post
        - dist
        - state
        - pin

      properties:
        id:
          type: number
        addressType:
          type: string
        userName:
          type: string
        pin:
          type: number
        contact:
          type: number
        line1:
          type: string
        line2:
          type: string
        post:
          type: string
        dist:
          type: string
        state:
          type: string
        createdOn:
          type: string
        updatedOn:
          type: string
        createdBy:
          type: string
        updatedBy:
          type: string















